### ISSUE TITLE
[Bug] Argument “"forward": false” don't work

### ISSUE THREAD

**Issue by Kristinita** [nsubiron/SublimeSuricate#7]
### 1. Summary

Commands of package [**Column Select**](https://github.com/ehuss/Sublime-Column-Select/blob/master/Default%20(Windows).sublime-keymap) incorrect run for me.

### 2. Expected behavior

If I run commands of Column Select with `Backward` word in a caption name, I get carriages in column to top of open file.

If I run commands of Column Select with `Forward` word in a caption name, I get carriages in column to bottom of open file.

### 3. Actual behavior

If I run commands of Column Select with `Forward` or `Backward` word in a caption name, I get carriages in column to bottom of open file. Argument `"forward": false` don't work for me.

### 4. Settings

My `User/Default.sublime-commands` file:

```json
[
    { "caption": "Column Select: By Lines Backward", "command": "column_select", "args": {"by": "lines", "forward": false}},
    { "caption": "Column Select: By Lines Forward", "command": "column_select", "args": {"by": "lines", "forward": true}},
    { "caption": "Column Select: By Pages Backward", "command": "column_select", "args": {"by": "pages", "forward": false}},
    { "caption": "Column Select: By Pages Forward", "command": "column_select", "args": {"by": "pages", "forward": true}},
    { "caption": "Column Select: By All Backward", "command": "column_select", "args": {"by": "all", "forward": false}},
    { "caption": "Column Select: By All Forward", "command": "column_select", "args": {"by": "all", "forward": true}}
]

```

Part of my `User/Default.suricate-profile`:

```json
"sasha_column_select_by_lines_backward": {
    "caption": "Column Select: By Lines Backward",
    "call": "sublime.column_select",
    "args": {
        "by": "lines",
        "forward": "false"
    }
},
"sasha_column_select_by_lines_forward": {
    "caption": "Column Select: By Lines Forward",
    "call": "sublime.column_select",
    "args": {
        "by": "lines",
        "forward": "true"
    }
},
"sasha_column_select_by_pages_backward": {
    "caption": "Column Select: By Pages Backward",
    "call": "sublime.column_select",
    "args": {
        "by": "pages",
        "forward": "false"
    }
},
"sasha_column_select_by_pages_forward": {
    "caption": "Column Select: By Pages Forward",
    "call": "sublime.column_select",
    "args": {
        "by": "pages",
        "forward": "true"
    }
},
"sasha_column_select_by_all_backward": {
    "caption": "Column Select: By All Backward",
    "call": "sublime.column_select",
    "args": {
        "by": "all",
        "forward": "false"
    }
},
"sasha_column_select_by_all_forward": {
    "caption": "Column Select: By All Forward",
    "call": "sublime.column_select",
    "args": {
        "by": "all",
        "forward": "true"
    }
},
```

### 5. Steps to reproduce

I reproduce the problem in a version of Sublime Text without plugins and user settings.

If I run my command use commands of `User/Default.sublime-commands` file, I get expected behavior.

If I run my command use commands of `User/Default.suricate-profile` file, I get actual behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126

Thanks.

**Comment by nsubiron** [comment]
Hi @Kristinita,
Sorry for taking so long to take a look at this issue. 

In case you haven't figured out yet, the issue is that you wrote true and false as strings, with quotes. Then when python converts this to bool it sees always true (non empty strings).

Just change your profile to

```json
"sasha_column_select_by_lines_backward": {
    "caption": "Column Select: By Lines Backward",
    "call": "sublime.column_select",
    "args": {
        "by": "lines",
        "forward": false
    }
},
"sasha_column_select_by_lines_forward": {
    "caption": "Column Select: By Lines Forward",
    "call": "sublime.column_select",
    "args": {
        "by": "lines",
        "forward": true
    }
},
// ...
```

This will generate exactly your Default.sublime-commands above.
